package betfair.model

enum class ApiNgExceptionErrorCode {
	TOO_MUCH_DATA,
	INVALID_INPUT_DATA,
	INVALID_SESSION_INFORMATION,
	NO_APP_KEY,
	NO_SESSION,
	UNEXPECTED_ERROR,
	INVALID_APP_KEY,
	TOO_MANY_REQUESTS,
	SERVICE_BUSY,
	TIMEOUT_ERROR,
	REQUEST_SIZE_EXCEEDS_LIMIT,
	ACCESS_DENIED
}
